### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [ahf/ahf.github.io#1]
This repo seems to be lacking a free license. I suggest AGPLv3 or later :)

**Comment by ahf** [comment]
Lol, no.

**Comment by pizzamaker** [comment]
Any particular reason for mass closing these issues?

**Comment by ahf** [comment]
Had you looked at the website of which this repository contains, you will find legal information at the bottom of the page.

You're welcome to come back with useful suggestions and code contributions to repositories I have worked on the day you start using it. This kind of mass creation of issues is stupid.

**Comment by pizzamaker** [comment]
A few of your projects really do have a legal notice, but some don't. I focused on the ones where there was no indication.
